### PR TITLE
Better check of username/password for ltv

### PR DESCRIPTION
**Pull request by fernandog**
When not username and not password, it didn't raise ConfigurationError
~~"if year is not None" is the same as "if year"~~ 

@ratoaq2

### CODE REVIEW

**Comment by Diaoul** [comment]
This is pure stylistic changes without unittests to back it up. `None` test is more accurate than testing as boolean.

**Comment by fernandog** [comment]
what about all[] that checks for 4 combinations of user/password instead of the existing 2?

**Comment by Diaoul** [comment]
The goal is to check that a parameter was actually passed even if using an optional argument, checking validity of username password is out of scope of subliminal.
If on the server the password should be 6 characters long, should subliminal check that too? I say no.

Actually I was thinking making those arguments positional but then the way the constuctor is called using provider configs should be changed too.
Maybe 2.0 is a good milestone for that change, if this introduces a breacking change.

**Comment by fernandog** [comment]
but for ltv to work it need username AND password. Only username, it will fail. Only password it will fail.

**Pull request closed without merging**
