### PR TITLE
Hotfix/subscenter url fix

### PR DESCRIPTION
**Pull request by ofir123**

### CODE REVIEW

**Comment by ofir123** [comment]
Done.

**Comment by ofir123** [comment]
Hi,
Can you please merge?
I see the tests are failing, but it has nothing to do with my changes :\
Thanks!

**Comment by ofir123** [comment]
Hey @diaoul,
Any updates? Any changes you need me to do?

**Comment by fernandog** [comment]
@ofir123 which PR should be used this or https://github.com/Diaoul/subliminal/pull/760 ?

**Comment by ofir123** [comment]
@fernandog Not related to the other one, so as far as I'm concerned this should be used :)

**Comment by fernandog** [comment]
@ofir123 but both try to fix subscenter right?  both fixes using the `h_version`

**Comment by ofir123** [comment]
New URL and h_version, yes.

**Comment by sharkykh** [comment]
Hey @ofir123, the cassettes are in the wrong folder.
```python
# They're in:
'tests/tests/cassettes/subscenter/*.yaml'
# while they should be in:
'tests/cassettes/subscenter/*.yaml'
```
Notice the double "tests"...

**Comment by ofir123** [comment]
SubsCenter closed their API access, and added a CAPTCHA :(
I've opened a new PR which removes this provider from subliminal (for now!)

**Pull request closed without merging**
