### PR TITLE
Add itasa provider + fixes

### PR DESCRIPTION
**Pull request by miigotu**
If you want to merge this that would be great, otherwise it is mostly to keep track of the patches we have in sickrage (I will try and keep this updated with your develop branch).

Now only adds itasa, in an unregistered state.

### CODE REVIEW

**Comment by miigotu** [comment]
not sure how to add cassettes, or fixup the opensubtitles cassettes.

If you can take care of that I can/will fix the other tests if needed.

**Comment by Diaoul** [comment]
Itasa isn't merged yet and code not reviewed. That means a lot of things can change like for legendas.
#536 is the reason why NapiProjekt is disabled.
Why add self.session to `__init__`? Why add "missing" ones? I have a warning on my IDE but nor pep8 neither pyflakes complain about this so why add code if it doesn't do anything? Sometimes one ought to be clever than best practices. Not sure it applies here anyway because documentation clearly states `initialize` is to be called if not using the `with` statement. I agree this is not ideal but I don't like the solution I'm left with. The alternative is to remove `initialize` and use `__init__` for that purpose, might be a good solution but I need to review consequences. PR accepted if you're willing to contribute.
You cannot catch everything that can go wrong in Python, don't bother with ConfigurationError on empty string. The idea here is to catch missing parameters that come together. If you filled the parameter with crap you cannot expect anything good from this.
Agreed for the raw string prefix in regex.

**Comment by miigotu** [comment]
Don't merge yet, I will make some adjustments, like not enabling napiprojekt and split out some of the other changes into smaller PR.

My IDE (editor really) shows pep8, pyflakes, and pylint output.

http://pylint-messages.wikidot.com/messages:w0232
http://pylint-messages.wikidot.com/messages:w0201

About the username/passwords:
Checking only against `None` is fine if it is only being used via cli, as the arguments cannot be empty strings easily. But when using it as a module I would have to explicitly do `sickbeard.BLAH_PASSWORD or None` to be sure it is handled correctly in the module.

While that is ok and easy for me to do, if someone does not know of this quirk and is implementing subliminal as a module into their project it can cause them headaches figuring out why it is trying to log in when they didn't provide a username or password and subsequently becoming a disabled_provider in the pool. It just seems to have no negative effect and makes it a little easier on 3rd parties, because an empty username or password can never log in to any site anyways.

I will contribute as much back as I can, because I think its silly to keep patching downstream and it's sort of part of the deal to help back when you use someone else's work.

**Comment by miigotu** [comment]
@Diaoul I split out the straight forward stuff into #617

**Comment by miigotu** [comment]
https://github.com/SickRage/SickRage/issues/1457

**Comment by fernandog** [comment]
A newer version is available in PR 804 from @Elettronik

**Pull request closed without merging**
