### PR TITLE
Opensubtitles VIP

### PR DESCRIPTION
**Pull request by ratoaq2**
Related to #952
Added a new provider `opensubtitlesvip` that just extends `opensubtitles`, but uses the VIP api URL

@darthShadow 
Could you please test it?

`subliminal --opensubtitles username password download --provider opensubtitlesvip <path>`

### CODE REVIEW

**Comment by darthShadow** [comment]
Doesn't seem to be working. 

Running:

`subliminal --opensubtitles '<username>' '<password>' download -v --provider opensubtitlesvip --language en <Movie>`

just gives me:

```
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%
Some providers have been discarded due to unexpected errors: opensubtitles
0 subtitle downloaded for <Movie>
```

Works fine with the regular `opensubtitles` provider.

`subliminal --opensubtitles '<username>' '<password>' download -v --provider opensubtitles --language en <Movie>`

```
Collecting videos  [####################################]  100%
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%
1 subtitle downloaded for <Movie>
```

Any way to enable additional logs? I already tried the `-v/--verbose` flag with no change.

**Comment by ratoaq2** [comment]
Use `--debug`

**Comment by darthShadow** [comment]
```
INFO:subliminal.core:Downloading subtitle <OpenSubtitlesSubtitle '1956237970' [en]>
ERROR:subliminal.utils:Unexpected error. Discarding provider opensubtitles
Traceback (most recent call last):
  File "/Users/darth/.pyenv/versions/3.6.2/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/core.py", line 166, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "/Users/darth/.pyenv/versions/3.6.2/lib/python3.6/site-packages/subliminal-2.1.0.dev0-py3.6.egg/subliminal/core.py", line 63, in __getitem__
    raise KeyError
KeyError
ERROR:subliminal.core:Invalid subtitle
WARNING:subliminal.core:Provider 'opensubtitles' is discarded
WARNING:subliminal.core:Provider 'opensubtitles' is discarded
WARNING:subliminal.core:Provider 'opensubtitles' is discarded
WARNING:subliminal.core:Provider 'opensubtitles' is discarded
```

**Comment by ratoaq2** [comment]
Thanks for the test. I'll fix this issue later today

**Comment by ratoaq2** [comment]
@darthShadow That should be fixed now. Let me know when you can retest it. Thanks

**Comment by darthShadow** [comment]
Working perfectly now.

**Pull request merged**
