### PR TITLE
Changed all log messages to proper formatting.

### PR DESCRIPTION
**Pull request by ofir123**
Log messages would cause errors in Python 3.5 because of bad formatting, so I've fixed all the log message lines.
Error screenshot:
image

### CODE REVIEW

**Comment by Diaoul** [comment]
The fix is wrong, the formatting should be done by the logger functions for performance optimization. I don't now why you have this error, maybe changing %r to %s will solve the issue? Can you try that?

**Comment by ofir123** [comment]
Still an issue.. even after changing to %s:
image

**Comment by ofir123** [comment]
Since most of the time is spent on HTTP access to the subtitle sites, is it really necessary to optimize log messages?

**Comment by Diaoul** [comment]
It's the way it is supposed to work see the [official doccumentation](https://docs.python.org/3/library/logging.html#logging.Logger.debug). I'll try to reproduce your issue but I think there is something wrong with your setup.

**Comment by Diaoul** [comment]
I'm closing since this is a local issue.

**Pull request closed without merging**
