### PR TITLE
Update README with newer infos

### PR DESCRIPTION
**Pull request by getzze**
Update badges and installation method.

### CODE REVIEW

**Review by ptrcnull — CHANGES_REQUESTED** [review]
two little things:
- discord badge: `[Discord](https://discord.gg/kXW6sWte9N)` ( @Diaoul, I generated a new invite code because yours was limited to 1 year; probably not a problem, but we can make an unlimited one so why not )
- maybe we should make the towncrier snippets capitalized?

**Comment by getzze** [comment]
FIY, the url of the discord badge gives an Invalid badge.

**Comment by ptrcnull** [comment]
ah, edited with the correct URL

**Comment by getzze** [comment]
> * maybe we should make the towncrier snippets capitalized?

Maybe this can be enforced at build time.

**Pull request merged**
