### PR TITLE
Python 3.6 is out

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by Diaoul** [comment]
This is against master not develop

**Comment by sharkykh** [comment]
@hugovk => #754

**Comment by hugovk** [comment]
Thanks!

By the way, you can click Edit on the right of the title and change the base branch to develop, as I did above.

Also, I recommend setting the default branch to develop in the repo settings, that way all new PRs go against that. (You could also mention to make it against develop in a [PR template](https://github.com/blog/2111-issue-and-pull-request-templates).)

**Comment by fernandog** [comment]
@hugovk you can't do that because new users will install develop branch instead of master

**Comment by hugovk** [comment]
Then the PR template would be helpful :)

**Comment by Diaoul** [comment]
This is mentioned in the [contributing notes](https://github.com/Diaoul/subliminal/blob/master/CONTRIBUTING.md#pull-requests).

**Pull request closed without merging**
