### PR TITLE
support multiple guessed formats

### PR DESCRIPTION
**Pull request by gsemet**
Clean fix for "Fixed `.lower()`" error.

Similar: #761, #775, #813, #814

### CODE REVIEW

**Comment by trillex** [comment]
Fails for me

`Downloading subtitles  [###---------------------------------]    9%  1d 16:48:03  American Dad! - S13E06 - Kiss Kiss Cam Cam - 1080p HDTV.mkv                                                               Some characters could not be decoded, and were replaced with REPLACEMENT CHARACTER.

Traceback (most recent call last):
  File "subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/providers/opensubtitles.py", line 79, in get_matches
    matches |= guess_matches(video, guessit(self.filename, {'type': 'episode'}))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/subtitle.py", line 223, in guess_matches
    if gfmt.lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
`

**Comment by Stibbons** [comment]
damned we can receive a list of list? can you print `guess['format']` ?

**Comment by trillex** [comment]
I'm absolutely not a python genius, but added print after it does it's thing:

```
    if video.format and 'format' in guess:
        gfmts = guess['format'] if isinstance(guess['format'], list) else [guess['format']]
        print(guess['format'])
        for gfmt in gfmts:
            if gfmt.lower() == video.format.lower():
                matches.add('format')
```

This works just fine on a working file, printing out the following:

`python3 subliminal download -l en -l da /volume1/Series/American\ Dad/Season\ 13/American\ Dad\!\ -\ S13E07\ -\ The\ Devil\ Wears\ a\ Lapel\ Pin\ -\ 1080p\ HDTV.mkv
Collecting videos  [####################################]  100%  /volume1/Series/American Dad/Season 13/American Dad! - S13E07 - The Devil Wears a Lapel Pin - 1Collecting videos  [####################################]  100%                                                                                                 
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  American Dad! - S13E07 - The Devil Wears a Lapel Pin - 1080p HDTV.mkvHDTV
HDTV
HDTV
HDTV
Downloading subtitles  [####################################]  100%             
Some providers have been discarded due to unexpected errors: legendastv
Downloaded 1 subtitle
`

But it never seems to actually populate the format on a non functioning file or I am calling it too late:

`python3 subliminal download -l en -l da /volume1/Series/American\ Dad/Season\ 13/American\ Dad\!\ -\ S13E06\ -\ Kiss\ Kiss\ Cam\ Cam\ -\ 1080p\ HDTV.mkv
Collecting videos  [####################################]  100%  /volume1/Series/American Dad/Season 13/American Dad! - S13E06 - Kiss Kiss Cam Cam - 1080p HDTV.Collecting videos  [####################################]  100%                                                                                                 
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  American Dad! - S13E06 - Kiss Kiss Cam Cam - 1080p HDTV.mkvCam

Traceback (most recent call last):
  File "subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/providers/opensubtitles.py", line 79, in get_matches
    matches |= guess_matches(video, guessit(self.filename, {'type': 'episode'}))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/subtitle.py", line 224, in guess_matches
    if gfmt.lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
`

**Comment by Stibbons** [comment]
I've updated my PR. it handles when `guess['format']` is a list or when `video.format` is a list (in your example, `video.format == ['Cam', 'HDTV']`.

**Comment by trillex** [comment]
Works for me, thank you. :)

**Comment by CyberMew** [comment]
The current fix now works properly for me as well. Cheers!

**Comment by Stibbons** [comment]
Fixed a similar issue in adic7ed plugin.

**Comment by ratoaq2** [comment]
Already fixed by 3121a75499779c7cc9eba059a4fa123cf5541027

**Pull request closed without merging**
