### PR TITLE
Fix Windows-1250 decoding

### LINKED ISSUE #1112: Fixup NapiProjekt subtitles encoding
sometimes the subtitles are getting returned as Windows-1250 instead of UTF-8; detect those cases and automatically convert them to UTF-8 whenever possible

marking as enhancement because it's NapiProjekt who's being silly and marking non-Unicode subtitles as UTF-8

### PR DESCRIPTION
**Pull request by ptrcnull**
closes #1112

### CODE REVIEW

**Comment by getzze** [comment]
Nice trick for checking the encoding, but I think we should also reorder the encoding to put the previous ones first, just to be on the safe side and not change old behaviors.

**Comment by ptrcnull** [comment]
sure, i'll reorder them to how they were before whenever i can

**Comment by getzze** [comment]
I can do it if you want

**Comment by ptrcnull** [comment]
alright, in this PR or in a separate one?

**Comment by getzze** [comment]
I'll commit here if you don't mind

**Comment by ptrcnull** [comment]
thanks!

**Pull request merged**
