### PR TITLE
Fixed `.lower()` error thrown on certain videos

### PR DESCRIPTION
**Pull request by Deathspike**
Fixed `.lower()` error thrown on certain videos due to `format` being a list. Or something. I don't actually understand anything that's going on here, but this change works on Py2+Py3 and seems to achieve my desired result - get subtitles even on those files.

Relevant issues:
https://github.com/Diaoul/subliminal/issues/761
https://github.com/Diaoul/subliminal/issues/775
https://github.com/Diaoul/subliminal/issues/813

### CODE REVIEW

**Comment by trillex** [comment]
Doesn't work for me on this file: American Dad! - S13E06 - Kiss Kiss Cam Cam - 1080p HDTV.mkv

**Comment by Deathspike** [comment]
@trillex What's the error?

**Comment by trillex** [comment]
Apologies, I forgot to paste it in. 

`American Dad! - S13E06 - Kiss Kiss Cam Cam - 1080p HDTV.mkv                   
Traceback (most recent call last):
  File "subliminal", line 11, in <module>
    sys.exit(subliminal())
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/providers/opensubtitles.py", line 79, in get_matches
    matches |= guess_matches(video, guessit(self.filename, {'type': 'episode'}))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/subliminal/subtitle.py", line 236, in guess_matches
    if video.format and 'format' in guess and isinstance(guess['format'], str if sys.version_info[0] >= 3 else basestring) and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
`

**Comment by fooper** [comment]
**Downloading subtitles  [##----------------------------------]    6%  0d 00:21:24  The.Deuce.S01E03.The.Principle.Is.All.720p.AMZN.WEBRip.DDP5.1.x264-NTb-postbot.mkv
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    load_entry_point('subliminal==2.1.0.dev0', 'console_scripts', 'subliminal')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/cli.py", line 400, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/core.py", line 215, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/core.py", line 215, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/providers/opensubtitles.py", line 78, in get_matches
    matches |= guess_matches(video, guessit(self.movie_release_name, {'type': 'episode'}))
  File "/usr/local/lib/python3.6/dist-packages/subliminal/subtitle.py", line 235, in guess_matches
    if video.format and 'format' in guess and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'
**

**Comment by fooper** [comment]
Tested Deathspike version, got similar error:
Downloading subtitles  [------------------------------------]    0%  0d 01:02:13  American.Gods.S01E07.PROPER.720p.HDTV.x264-GET_WEB.mkvINFO:subliminal.core:Listing subtitles with provider 'addic7ed' and languages {<Language [sv]>}
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages {<Language [sv]>}
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [sv]>}
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviehash': '3b93566e98443176', 'moviebytesize': '977124796', 'sublanguageid': 'swe'}, {'imdbid': '5665584', 'sublanguageid': 'swe'}, {'tag': 'American.Gods.S01E07.PROPER.720p.HDTV.x264-GET_WEB.mkv', 'sublanguageid': 'swe'}, {'query': 'American Gods', 'season': 1, 'episode': 7, 'sublanguageid': 'swe'}]
DEBUG:subliminal.providers.addic7ed:Getting show id with year
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages {<Language [sv]>}
INFO:subliminal.core:Skipping provider 'shooter': no language to search for
DEBUG:subliminal.providers.addic7ed:Getting show id
INFO:subliminal.core:Skipping provider 'subscenter': no language to search for
INFO:subliminal.providers.podnapisi:Searching subtitles {'sXML': 1, 'sL': 'sv', 'sK': 'American Gods', 'sTS': 1, 'sTE': 7, 'sY': 2017}
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages {<Language [sv]>}
INFO:subliminal.core:Listing subtitles with provider 'tvsubtitles' and languages {<Language [sv]>}
INFO:subliminal.providers.addic7ed:Getting the page of show id 4642, season 1
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': '62b91c216e4dd7e344c3597521066bda'}
INFO:subliminal.providers.tvsubtitles:Getting the page for episode 66268
ERROR:subliminal.core:Unexpected error in provider 'addic7ed'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/subliminal/core.py", line 118, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/providers/addic7ed.py", line 273, in list_subtitles
    return [s for s in self.query(video.series, video.season, video.year)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/providers/addic7ed.py", line 238, in query
    raise TooManyRequests()
subliminal.exceptions.TooManyRequests
INFO:subliminal.core:Discarding provider addic7ed
DEBUG:subliminal.providers.thesubdb:No subtitles found
DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'iaJE' [sv]>
DEBUG:subliminal.providers.opensubtitles:No subtitles found
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '326705' [en]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '327133' [en]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '326708' [fr]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '327673' [pt]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '326718' [pt]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '326719' [pt]>
DEBUG:subliminal.providers.tvsubtitles:Found subtitle <TVsubtitlesSubtitle '326869' [ro]>
INFO:subliminal.score:Computing score of <PodnapisiSubtitle 'iaJE' [sv]> for video <Episode ['American Gods', 2017, 1x7]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 359, 'series': 180, 'year': 90, 'season': 30, 'episode': 30, 'release_group': 15, 'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}

DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider thesubdb
INFO:subliminal.core:Terminating provider tvsubtitles
INFO:subliminal.core:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
INFO:subliminal.core:Terminating provider addic7ed
INFO:subliminal.providers.addic7ed:Logging out
DEBUG:subliminal.providers.addic7ed:Logged out
Traceback (most recent call last):
  File "/usr/local/bin/subliminal", line 11, in <module>
    load_entry_point('subliminal==2.0.5', 'console_scripts', 'subliminal')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/cli.py", line 403, in download
    hearing_impaired=hearing_impaired, only_one=single)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/core.py", line 211, in download_best_subtitles
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/core.py", line 211, in <listcomp>
    for s in subtitles], key=operator.itemgetter(1), reverse=True)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/score.py", line 106, in compute_score
    matches = subtitle.get_matches(video)
  File "/usr/local/lib/python3.6/dist-packages/subliminal/providers/podnapisi.py", line 65, in get_matches
    matches |= guess_matches(video, guessit(release, {'type': 'episode'}))
  File "/usr/local/lib/python3.6/dist-packages/subliminal/subtitle.py", line 236, in guess_matches
    if video.format and 'format' in guess and isinstance(guess['format'], str if sys.version_info[0] >= 3 else basestring) and guess['format'].lower() == video.format.lower():
AttributeError: 'list' object has no attribute 'lower'

**Comment by Stibbons** [comment]
+1

**Comment by marcelpaulo** [comment]
I'm getting the same error but with file _The.Hitman\'s.Bodyguard.2017.720p.BluRay.x264-\[YTS.AG\].mp4_. I'm running master dd74383d1cba82829ce720f2e439a65d13ffe7ef with python3.

```
INFO:subliminal.core:Scanning video "The.Hitman's.Bodyguard.2017.720p.BluRay.x264-[YTS.AG].mp4" in ''
DEBUG:subliminal.core:Size is 904255341
DEBUG:subliminal.core:Computed hashes {'opensubtitles': 'cce765290c37ae71', 'shooter': '53b83195f3d50a135ea41e3ee26000ca;8f5247254568eaa583b66b31350fc88f;54bf3580c568a5c23117d1ba4a990273;bd75025c0af5c7a8d301db750a4c7f28', 'thesubdb': 'e62a05b658b0d377eb7d361934944272', 'napiprojekt': 'bfd554875f6d75f85b2c84f9e7e5fd9d'}
DEBUG:subliminal.core:Found subtitles {}
INFO:subliminal.core:Refining video with metadata
DEBUG:subliminal.refiners.metadata:Unsupported video extension .mp4
INFO:subliminal.core:Refining video with omdb
WARNING:subliminal.refiners.omdb:No results
Collecting videos  [####################################]  100%                                                           
1 video collected / 0 video ignored / 0 error
Downloading subtitles  [####################################]  100%  The.Hitman's.Bodyguard.2017.720p.BluRay.x264-[YTS.AG].mp4INFO:subliminal.core:Skipping provider 'addic7ed': not a valid video
INFO:subliminal.core:Listing subtitles with provider 'legendastv' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider legendastv
INFO:subliminal.core:Listing subtitles with provider 'opensubtitles' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging in
INFO:subliminal.core:Listing subtitles with provider 'podnapisi' and languages {<Language [en]>}
INFO:subliminal.core:Initializing provider podnapisi
INFO:subliminal.providers.podnapisi:Searching subtitles {'sXML': 1, 'sL': 'en', 'sK': "The Hitman's Bodyguard", 'sY': 2017}
INFO:subliminal.core:Listing subtitles with provider 'shooter' and languages {<Language [en]>}
INFO:subliminal.core:Skipping provider 'subscenter': no language to search for
INFO:subliminal.core:Initializing provider shooter
INFO:subliminal.core:Listing subtitles with provider 'thesubdb' and languages {<Language [en]>}
INFO:subliminal.core:Skipping provider 'tvsubtitles': not a valid video
INFO:subliminal.core:Initializing provider thesubdb
DEBUG:subliminal.providers.shooter:Searching subtitles {'filehash': '53b83195f3d50a135ea41e3ee26000ca;8f5247254568eaa583b66b31350fc88f;54bf3580c568a5c23117d1ba4a990273;bd75025c0af5c7a8d301db750a4c7f28', 'pathinfo': "/home/paulo/watch/The.Hitman's.Bodyguard.2017.720p.BluRay.x264-[YTS.AG].mp4", 'format': 'json', 'lang': 'eng'}
INFO:subliminal.providers.thesubdb:Searching subtitles {'action': 'search', 'hash': 'e62a05b658b0d377eb7d361934944272'}
DEBUG:subliminal.providers.legendastv:Found subtitle <LegendasTVSubtitle '59a1d7bede526-the.hitmans.bodyguard.2017.1080p.webrip.dd5.1.x264-nogrp-english.srt' [en]>
DEBUG:subliminal.providers.legendastv:Found subtitle <LegendasTVSubtitle '59a1d7bede526-the.hitmans.bodyguard.2017.720p.webrip-forced.srt' [en]>
DEBUG:subliminal.providers.thesubdb:Found subtitle <TheSubDBSubtitle 'e62a05b658b0d377eb7d361934944272-pt-BR' [pt-BR]>
DEBUG:subliminal.providers.opensubtitles:Logged in with token 'd2Gb1qYPdwCBHhYGALn2OsR5fw0'
INFO:subliminal.providers.opensubtitles:Searching subtitles [{'moviehash': 'cce765290c37ae71', 'moviebytesize': '904255341', 'sublanguageid': 'eng'}, {'tag': "The.Hitman's.Bodyguard.2017.720p.BluRay.x264-[YTS.AG].mp4", 'sublanguageid': 'eng'}, {'query': 'The Hitmans Bodyguard', 'sublanguageid': 'eng'}]
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955735535' [en]> by moviehash
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955735535' [en]> by tag
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955659575' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955659416' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955659683' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955659636' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955659568' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955678350' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955659639' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955735453' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955736176' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955735535' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955735467' [en]> by fulltext
DEBUG:subliminal.providers.opensubtitles:Found subtitle <OpenSubtitlesSubtitle '1955670805' [en]> by fulltext
DEBUG:subliminal.providers.podnapisi:Found subtitle <PodnapisiSubtitle 'IcFE' [en]>
DEBUG:subliminal.providers.shooter:No subtitles found
INFO:subliminal.score:Computing score of <LegendasTVSubtitle '59a1d7bede526-the.hitmans.bodyguard.2017.1080p.webrip.dd5.1.x264-nogrp-english.srt' [en]> for video <Movie ["The Hitman's Bodyguard", 2017]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 119, 'title': 60, 'year': 30, 'release_group': 15, 'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'video_codec', 'title', 'year'}
INFO:subliminal.score:Computed score 92 with final matches {'video_codec', 'title', 'year'}
INFO:subliminal.score:Computing score of <LegendasTVSubtitle '59a1d7bede526-the.hitmans.bodyguard.2017.720p.webrip-forced.srt' [en]> for video <Movie ["The Hitman's Bodyguard", 2017]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 119, 'title': 60, 'year': 30, 'release_group': 15, 'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'video_codec', 'resolution', 'title', 'year'}
INFO:subliminal.score:Computed score 94 with final matches {'video_codec', 'resolution', 'title', 'year'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1955735535' [en]> for video <Movie ["The Hitman's Bodyguard", 2017]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 119, 'title': 60, 'year': 30, 'release_group': 15, 'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'resolution', 'video_codec', 'hash', 'format', 'title', 'year'}
DEBUG:subliminal.score:Keeping only hash match
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 120 with final matches {'hash', 'hearing_impaired'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1955735535' [en]> for video <Movie ["The Hitman's Bodyguard", 2017]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 119, 'title': 60, 'year': 30, 'release_group': 15, 'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}
DEBUG:subliminal.score:Found matches {'resolution', 'video_codec', 'format', 'title', 'year'}
DEBUG:subliminal.score:Matched hearing_impaired
INFO:subliminal.score:Computed score 102 with final matches {'resolution', 'video_codec', 'format', 'hearing_impaired', 'title', 'year'}
INFO:subliminal.score:Computing score of <OpenSubtitlesSubtitle '1955659575' [en]> for video <Movie ["The Hitman's Bodyguard", 2017]> with {'hearing_impaired': False}
DEBUG:subliminal.score:Using scores {'hash': 119, 'title': 60, 'year': 30, 'release_group': 15, 'format': 7, 'audio_codec': 3, 'resolution': 2, 'video_codec': 2, 'hearing_impaired': 1}

DEBUG:subliminal.core:Terminating initialized providers
INFO:subliminal.core:Terminating provider legendastv
INFO:subliminal.core:Terminating provider podnapisi
INFO:subliminal.core:Terminating provider shooter
INFO:subliminal.core:Terminating provider thesubdb
INFO:subliminal.core:Terminating provider opensubtitles
INFO:subliminal.providers.opensubtitles:Logging out
DEBUG:subliminal.providers.opensubtitles:Logged out
Traceback (most recent call last):
  File "/home/paulo/.local/bin/subliminal", line 11, in <module>
    load_entry_point('subliminal==2.0.5', 'console_scripts', 'subliminal')()
  File "/home/paulo/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/paulo/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/paulo/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/paulo/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.0.5-py3.6.egg/subliminal/cli.py", line 403, in download
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.0.5-py3.6.egg/subliminal/core.py", line 211, in download_best_subtitles
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.0.5-py3.6.egg/subliminal/core.py", line 211, in <listcomp>
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.0.5-py3.6.egg/subliminal/score.py", line 106, in compute_score
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.0.5-py3.6.egg/subliminal/providers/opensubtitles.py", line 98, in get_matches
  File "/home/paulo/.local/lib/python3.6/site-packages/subliminal-2.0.5-py3.6.egg/subliminal/subtitle.py", line 235, in guess_matches
AttributeError: 'list' object has no attribute 'lower'

```

**Comment by Stibbons** [comment]
Call for merge

**Comment by fernandog** [comment]
Related to https://github.com/Diaoul/subliminal/pull/769

**Comment by fernandog** [comment]
@Deathspike i cant fix the PR as you PRed against master and not develop.

**Comment by fernandog** [comment]
I created another PR cherry-picking your commit. closing this one

**Comment by kim0** [comment]
@fernandog .. Thanks for merging .. How can users install this ? (I assume it'll take some time to appear in pip)

**Comment by fernandog** [comment]
It's not merged. Needs review from another user how knows guessit better

**Comment by marcelpaulo** [comment]
Hey @fernandog, why this fix is not merged into `develop` ? It looks like this is the only branch which hasn't been merged into `develop`. The bug which it fixes occurs so frequently that I'm still installing from this branch.

**Comment by fernandog** [comment]
Well, @ratoaq2 and @Diaoul need to decide the best fix for this issue. Recently rato changed guessit thinking about this issue I'm subliminal

**Pull request closed without merging**
