### PR TITLE
Cli providers params

### LINKED ISSUE #1179: Pass arguments to providers through the CLI
Right now we can pass arguments to the providers only through the config file.
Because of the extension system, we cannot set the arguments of each and every providers as hard-coded options for the CLI. However, `click` allows to add dynamic options!

The scheme for the provider (and refiner) arguments I thought about is:
`--provider.opensubtitles.username=user`

The variable names are `_provider__opensubtitles__username`, note the double underscores to be able to split the variables if an underscore is present in an argument name or provider name, for instance `_provider__addic7ed__allow_searches`.

We could also add support for passing options to the CLI with environment variables (easy to do with `click`).
The scheme would be:
`SUBLIMINAL_PROVIDER_OPENSUBTITLES_USERNAME` (with single underscores).

### PR DESCRIPTION
**Pull request by getzze**
closes #1179 

This is a breaking change, for command line usage.

### CODE REVIEW

**Comment by etherealite** [comment]
I like a lot of what I'm seeing here, getting rid of the click-option-group package is nice. Keeping all of the click usage confined to one module is clean.

 I think I would prefer if this could be made a little bit closer to the approach that the Typer project uses. It combines using docstrings with an annotated function signature. See it in action in the [CLI Options with Help](https://typer.tiangolo.com/tutorial/options/help/) section of their docs.

I would really really really prefer to not have anything syntactic in the doc strings. Using the doc string in the generated docs is great, but don't parse it.

```python
class SomeProvider(Provider):
    def __init__(
            self,
            username: Annotated[str, Option(help="OpenSubtitles username")],
	    password: Annotated[str, Option(help="OpenSubtitles password")],
	)
        """
        Downloads subtitles from OpenSubtitles.
        
        [username] and [password] are required if not set in config.toml
        """
        ...
```

Instead, use the signature annotations for anything where you'd need to parse a docstring and inline the docstring into the generated documentation.


I think it's worth raising that hard coding the parameters that an extension can use is pretty restrictive. Who knows what kind of requirements might be needed by some future extension. Is there not some way to allow more flexibility in this regard? 

Perhaps allowing aping a narrow subset of click's api and exposing that to extensions would work?

**Comment by getzze** [comment]
I like the usage of Annotated type hints, thanks, it's much better than parsing the docstring.

> I think it's worth raising that hard coding the parameters that an extension can use is pretty restrictive. Who knows what kind of requirements might be needed by some future extension. Is there not some way to allow more flexibility in this regard?

It's not the case! It takes all the arguments of the `__init__` method and transform them into `click` options. I hard-coded arguments to SKIP for the refiners but not the providers.

**Comment by etherealite** [comment]
I'll try and incorporate this and the examples you gave in #1177 into my provider soon.

**Comment by getzze** [comment]
I decided not to use `Annotated` type hint and parse the docstring. If needed we can do it in another PR.

**Pull request merged**
