### PR TITLE
Ignore "Sample" folders (scene) and sample.mkv|avi|etc. files

### PR DESCRIPTION
**Pull request by fernandog**
Fix https://github.com/Diaoul/subliminal/issues/580

@duramato ok with scene rule?

### CODE REVIEW

**Comment by duramato** [comment]
Yes.
But keep in mind sample files themselfs aren't just `sample.extension`.

**Comment by fernandog** [comment]
@duramato guessit detects the `sample` in release name ? if yes, which property?

**Comment by duramato** [comment]
Don't think it doesn't.

**Comment by duramato** [comment]
https://github.com/guessit-io/guessit/issues/516

**Pull request merged**
