### PR TITLE
Save country data from GUESSIT result 

### PR DESCRIPTION
**Pull request by shlomiLan**
This PR is for fixing #840 .

### CODE REVIEW

**Comment by fernandog** [comment]
@shlomiLan thanks. I changed branch to develop. All good now.

What about the TVDB thing you said ?

**Comment by shlomiLan** [comment]
@fernandog Same tests are failed, but I don't think that it because things that I changed, how can I be sure?

**Comment by fernandog** [comment]
you need to review all failing tests

like this error for example:
Now it matches title and imdb_id but it's not expected (at least not in develop code). Now with your PR it seems that is matching that now

>       assert matches == {'series', 'year', 'season', 'episode', 'format', 'video_codec'}
E       AssertionError: assert set(['episode...'title', ...]) == set(['episode'...dec', 'year'])
E         Extra items in the left set:
E         'imdb_id'
E         'title'

**Comment by fernandog** [comment]
@Diaoul what do you think of this? its not wanted/not good he can change strategy

**Comment by ratoaq2** [comment]
Fixed by 676354ca8b341432e416e42d8d8500a96d0af398

**Pull request closed without merging**
