### PR TITLE
Small adjustments, split out from #605

### PR DESCRIPTION
**Pull request by miigotu**
Use raw strings for regex literals
Tweak username and password conditionals in providers to also catch empty strings as invalid
Add some missing `__init__` methods, and add class properties that were defined outside of `__init__`

### CODE REVIEW

**Comment by Diaoul** [comment]
Raw strings with 25ece03102cd43581c972cc0bd99d4bd47140392

**Comment by miigotu** [comment]
I still think the other tweaks are beneficial, but you're the boss =P

**Comment by Diaoul** [comment]
That's why I didn't close :)

**Comment by miigotu** [comment]
bwaha, ok. Ill fix the conflicts then xD

**Comment by fernandog** [comment]
Merged in https://github.com/Diaoul/subliminal/commit/2d266cdae93129d7c7bd5ffe73e25fac2200cc94#diff-c9c71e810cede81785a6732f7362417a

**Pull request closed without merging**
