### PR TITLE
Subscenter support

### PR DESCRIPTION
**Pull request by ofir123**
Added support for the largest hebrew subs site, called Subscenter.

### CODE REVIEW

**Comment by Diaoul** [comment]
Please rebase against master and add unit tests

**Comment by Diaoul** [comment]
Can you squash your commits and rebase against develop branch please? The diff shows unrelated stuff.

**Comment by ofir123** [comment]
Hey!
Sorry, I didn't have a lot of time lately.
I'll tend to it over the next week!

**Comment by Diaoul** [comment]
No problem, thanks for the update.

**Comment by ofir123** [comment]
All done!
Can you please review and merge before any big changes break it again?

Thanks!
Ofir

**Pull request closed without merging**
