### PR TITLE
Use splitext to get extension and compare lowercase

### PR DESCRIPTION
**Pull request by fernandog**
Fixes https://github.com/Diaoul/subliminal/issues/861

@morpheus65535 can you test this please?

### CODE REVIEW

**Comment by morpheus65535** [comment]
@stefandevo You can try this? You were the one having an issue with this. Thanks!

**Comment by morpheus65535** [comment]
I'Ve tested it myself and it work. Thanks!

**Comment by fernandog** [comment]
splitext() is specifically written for returning the extension

**Comment by ratoaq2** [comment]
Yes, but that's not needed. The only required change was to add lower before endswith.

**Pull request merged**
