### PR TITLE
Add aRGENTeaM provider

### PR DESCRIPTION
**Pull request by mmiraglia**
aRGENTeaM is a great spanish subtitle provider, especially for the latin community. Only episodes subtitles are supported in this first release of the provider.

### CODE REVIEW

**Comment by mmiraglia** [comment]
I fixed some errors from the previus PR. I hope this time everything is OK.

**Comment by fernandog** [comment]
@mmiraglia you missed this implementation: https://github.com/Diaoul/subliminal/pull/778

**Comment by mmiraglia** [comment]
@fernandog I relied on the develop branch ... I do not understand how I missed it :(
Anyway, can you help me to incorporate the implementation to this branch? Even with a googled link :)

**Comment by mmiraglia** [comment]
@fernandog my bad! Finally I understood your requirement. Please, check it and give me your feedback.

**Comment by fernandog** [comment]
@mmiraglia remove the commented code

**Comment by fernandog** [comment]
@mmiraglia you also missed the cassettes. When you run the test it creates a cassette. Check the test foldee

**Comment by mmiraglia** [comment]
I'm sorry @fernandog . As I mentioned earlier, I am new developing python and github.

**Comment by ratoaq2** [comment]
I squashed your commits and fixed remaining issues to have a functional provider

Fixed by 41f5c155c5ebacf06bfac592de39d3d568b29d1a
Thanks

**Pull request closed without merging**
