### PR TITLE
Use regex to find external subtitles

### PR DESCRIPTION
**Pull request by getzze**
In the search_external_subtitles function, only subtitles of the form <video_name>.eng.srt. With also some errors, like  <video_name>[eng].srt is matched to `eng]`.
Using a regex allow for a better match, of the form en, eng, en_GB or eng_GB.

### CODE REVIEW

**Comment by Diaoul** [comment]
Please add unitttests

**Comment by getzze** [comment]
Ok, I changed the regex to finally pass all the tests and I added two new tests. Sorry I am not used to testing, although it is a very good practice!

**Comment by Diaoul** [comment]
Are media players able to read subtitles like that? What's the use case?

**Comment by Diaoul** [comment]
Say you have a movie in french `Something.2015.[FR].mkv` with `Something.2015.[FR].srt`, how does that behave?

**Pull request closed without merging**
