### PR TITLE
Added Argenteam Provider for episodes only

### PR DESCRIPTION
**Pull request by mmiraglia**
aRGENTeaM is a great spanish subtitle provider, especially for the latin community. Only episodes subtitles are supported in this first release of the provider.

### CODE REVIEW

**Comment by fernandog** [comment]
@mmiraglia you can't commit to master. will change branch

**Comment by fernandog** [comment]
@mmiraglia also you didn't created a feature branch

**Comment by mmiraglia** [comment]
Thx Fernando!
I'm new in git and github, i'm still learning :)
BTW, my english isn't good, can i post in spanish?

**Comment by mmiraglia** [comment]
Ok, i'll close this PR and create a new one with a feature/add_argenteam branch based on the develop branch of this project when pass the Travis CI tests.
Thanks Fernando for your support!!

**Pull request closed without merging**
