### PR TITLE
Improve the visibility of Discord channel and add contributions section to readme

### PR DESCRIPTION
**Pull request by etherealite**
Discord badge now better matches dimensions and style of the other badges.

Added Discord as the community entry in the table of contents. 

I've removed the link to the gitter since it was never used and likely never will be.

### CODE REVIEW

**Comment by getzze** [comment]
Thanks, pre-commit is failing because of a line too long.

**Comment by etherealite** [comment]
I'll get to this as soon as I can.

**Comment by etherealite** [comment]
It now passes when I run `pre-commit run doc8 --all-files`, let me know if any further changes are required.

**Comment by getzze** [comment]
Great thanks!

**Pull request merged**
