### PR TITLE
Match release_group when both video and subtitle doesn't have it

### PR DESCRIPTION
**Pull request by fernandog**
This is a proposal to fix my issue:
https://github.com/Diaoul/subliminal/issues/652

If both subtitles and video doesn't have release_group, we assume is a match on release_group

@ratoaq2 suggested this: https://github.com/Diaoul/subliminal/issues/652#issuecomment-244585101 that we can consider too

What do you think @Diaoul ?
If you don't like it at least we can discuss alternative solutions

### CODE REVIEW

**Comment by ratoaq2** [comment]
I don't agree with my proposal from 10 months ago since I have a more mature opinion on that. 

From my point of view the compute score function should receive more information, not only a set of which fields have matched. 
Maybe it should be a dict with matched fields as key and the actual value as values. 
Then the score function can decide how to score matches with or without values

**Comment by Diaoul** [comment]
I tend to agree with @ratoaq2, there shouldn't be any logic in `guess_matches`, it should only parse tokens so that `compute_score` can do its job.

**Comment by fernandog** [comment]
@Diaoul Its a big change in code right?

**Comment by Diaoul** [comment]
The video object and the subtitle object are already passed to the compute_score function.

Anyway, if the release_group isn't present in the video name it means it has probably been renamed, matching the absence of release_group isn't a good idea here. It may suit your use case but I can see side effects.

**Comment by duramato** [comment]
>> ...if the release_group isn't present in the video name it means it has probably been renamed...

Incorrect, there are many _releases_ that don't have a release group in them because they where released like that.

**Pull request closed without merging**
