### PR TITLE
Fix napiprojekt

### PR DESCRIPTION
**Pull request by getzze**
Requires https://github.com/Diaoul/subliminal/pull/1103

The provider was completely broken: now the raw content is correctly downloaded and following #1103, the subtitles are correctly decoded and validated.

Also add type hints

### CODE REVIEW

**Comment by ptrcnull** [comment]
oh? i was able to download stuff from napiprojekt a while ago, i think i even closed an issue with debug logs and "it works for me"

**Comment by ptrcnull** [comment]
weeeird, i could swear i downloaded some Polish subs from NapiProjekt with subliminal a while ago; i'll test out the fix in a sec

**Comment by ptrcnull** [comment]
```
ERROR:subliminal.utils:Unexpected error. Provider napiprojekt
Traceback (most recent call last):
  File "/home/patrycja/dev/subliminal/subliminal/core.py", line 116, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/patrycja/dev/subliminal/subliminal/providers/napiprojekt.py", line 172, in list_subtitles
    return [s[0] for s in [self.query(lang, video.hashes['napiprojekt']) for lang in languages] if len(s) > 0]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/patrycja/dev/subliminal/subliminal/providers/napiprojekt.py", line 164, in query
    subtitle = self.subtitle_class(language=language, video_hash=video_hash)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/patrycja/dev/subliminal/subliminal/providers/napiprojekt.py", line 59, in __init__
    super().__init__(language, fps=fps)
TypeError: Subtitle.__init__() got an unexpected keyword argument 'fps'
```
it doesn't seem to be a property on Subtitle, am i missing some pull request?

**Comment by ptrcnull** [comment]
ah, don't mind me, i forgot to apply #1103 to my local branch

**Comment by getzze** [comment]
You are missing #1103

**Comment by ptrcnull** [comment]
okay, so there's one issue with this PR currently: it writes the subtitles to a `.srt`, but in my case it actually downloaded MicroDVD subs:
```
$ head Now.You.See.Me.2.2016.1080p.BluRay.x264.AC3-JYK.pl.srt 
{1}{1}24
{310}{404}www.NapiProjekt.pl - nowa jakość napisów.|Napisy zostały specjalnie dopasowane do Twojej wersji filmu.
{406}{526}::PROJECT HAVEN MOVIES::|/prezentuje
{526}{670}Tłumaczenie: GabryS|Korekta: peciaq
{672}{734}Przepraszam.
{754}{835}Przepraszam.|Przechodzę.
{864}{984}/Dzisiaj tak zwany magik Lionel Shrike|/znów żałośnie szuka rozgłosu,
{984}{1068}/dokonując "niemożliwego".
{1068}{1150}/Sejf jest z najtrwalszego żelaza.
{1150}{1229}/Nie można go przeciąć|/ani wyważyć.
```

**Comment by getzze** [comment]
Good catch in `subtitle.py`, `get_subtitle_path` adds `srt` as an extension as a default.

**Comment by getzze** [comment]
Maybe the subtitle extension can be fixed in another PR

**Comment by getzze** [comment]
One question though, all the subtitles from napiprojekt are Microdvd subs?

**Comment by ptrcnull** [comment]
nope, we'd need to get subtitle type detection ( or well, i'm pretty sure the API does return it in some way ) and then proper extension matching

**Comment by ptrcnull** [comment]
( for the record, from the 19 samples that i got, only 2 of them are actually MicroDVD `.sub`, all the rest are SubRip `.srt` )

**Comment by getzze** [comment]
OK, the 3 examples used in the tests are `.sub` or `.srt`? We should test for both formats.

First I made the `expected_format`  attributes of `Subtitle` a list of possible formats, but then I thought it would be unlikely and just made it a string...

**Comment by ptrcnull** [comment]
they seem to all be MicroDVD - i can change one of the tests to get a known .srt subtitle instead

**Comment by ptrcnull** [comment]
ah, even worse! some subtitles are MicroDVD encoded in [Windows-1250][1], even though the HTTP headers indicate UTF-8

[1]: https://en.wikipedia.org/wiki/Windows-1250

**Comment by getzze** [comment]
> they seem to all be MicroDVD - i can change one of the tests to get a known .srt subtitle instead

It would be great yes.

I would prefer to accept this PR to keep all of the type hint changes and then fix everything in another PR. And add the tests with `.srt` files to this other PR.

**Comment by getzze** [comment]
I'm going to merge this so I can make some other changes.

We still have to add a test for a subtitle in the `.srt` format.

**Pull request merged**
