### PR TITLE
Hotfix/subscenter removal

### PR DESCRIPTION
**Pull request by ofir123**
SubsCenter started requiring CAPTCHA, so I've removed the provider until a better solution will be found.

### CODE REVIEW

**Comment by Diaoul** [comment]
Can you squash commits?

**Comment by ofir123** [comment]
Done!

**Comment by Diaoul** [comment]
Is the failing test related to this PR?

**Comment by Diaoul** [comment]
Nvm it is not.
LGTM !

Thanks

**Pull request merged**
